---
spring:
  application:
    name: jobx
server:
  port: 9090
management:
  server:
    port: 9091
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    id: my-register
    timeout: 30000
  protocol:
    port: 12345
    name: dubbo
    id: dubbo
    status: client
  application:
    name: jobx-server
    id: jobx-server
  qos:
    port: 22223
  consumer:
    client: netty4
