server:
  port: 8080

spring:
  application:
    name: jobX
#dubbo--------------------------------
dubbo:
  application:
    id: jobx-server
    name: jobx-server
  server: true
  qos:
    port: 22223
  registry:
    id: my-register
    address: 127.0.0.1:2181
    protocol: zookeeper
    client: curator
    timeout: 30000
    consumer:
      client: netty4

# Enables Dubbo All Endpoints
management:
  server:
    port: 8081

  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown.enabled: true
    dubbo-configs.enabled: true
    dubbo-services.enabled: true

jobx:
  provide:
    version: 2.0.0

#dubbo end --------------------------------





